package com.dolphin.stock.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;

public final class StockAnalysisModels {
    private StockAnalysisModels() {}

    public record StrategyConfig(
            String name,
            int minScore,
            BigDecimal minPrice,
            BigDecimal maxPrice,
            BigDecimal minAverageTurnover,
            int minListingDays,
            BigDecimal maxSinglePosition,
            BigDecimal maxIndustryPosition,
            BigDecimal maxTotalPosition,
            BigDecimal hardStopLoss,
            BigDecimal trailingStopLoss,
            int sellScoreThreshold) {}

    public record ScoringModel(
            String strategyId,
            int version,
            LocalDateTime generatedAt,
            String provider,
            String model,
            int businessModelWeight,
            int industryProspectWeight,
            int competitiveAdvantageWeight,
            int financialQualityWeight,
            int growthWeight,
            int valuationWeight,
            int catalystWeight,
            int riskWeight,
            int totalWeight,
            boolean aiAdjusted,
            String adjustmentSummary,
            List<String> adjustmentReasons,
            BigDecimal confidence,
            String credibilityBasis) {
        public static ScoringModel defaultModel() {
            return new ScoringModel("value-quality-100", 1, null, "SYSTEM", "value-quality-v1",
                    15, 15, 15, 20, 15, 10, 5, 5, 100, false,
                    "股票投资价值模型：好行业 × 好公司 × 好业绩 × 合理估值 × 合适价格",
                    List.of("商业模式、行业前景、竞争优势、财务质量、成长性、估值、催化剂、风险"),
                    BigDecimal.ZERO, "多渠道行情、财务、公告和AI资料按披露时间入库后评分");
        }

        // 兼容历史调用方；新业务统一使用上面的8个模块字段。
        public int trendWeight() { return industryProspectWeight; }
        public int fundamentalWeight() { return financialQualityWeight; }
        public int momentumWeight() { return growthWeight; }
        public int volumePriceWeight() { return valuationWeight; }
        public int capitalWeight() { return catalystWeight; }
        public int qualityValuationWeight() { return competitiveAdvantageWeight; }
        public int aiSuggestionWeight() { return riskWeight; }
    }

    /** Database-backed model metadata shown in the model center. */
    public record ModelStatus(
            String modelKey,
            int version,
            LocalDateTime generatedAt,
            boolean persisted,
            boolean databaseAvailable,
            long persistedRecords,
            long usedRecords,
            long usageCount,
            LocalDateTime lastUsedAt,
            int score,
            String dataSource) {}

    /** Parameters generated by the hourly AI job and used to calculate plan execution probability. */
    public record TradeSuccessRateModel(
            String stockCode,
            int version,
            LocalDateTime generatedAt,
            String provider,
            String model,
            BigDecimal baseProbability,
            BigDecimal confidenceWeight,
            BigDecimal aiPriceMatchBonus,
            BigDecimal aiPriceMismatchPenalty,
            BigDecimal technicalMatchBonus,
            BigDecimal technicalMismatchPenalty,
            BigDecimal hardRiskPenalty,
            BigDecimal warningPenalty,
            BigDecimal minProbability,
            BigDecimal maxProbability,
            BigDecimal confidence,
            String summary,
            List<String> reasons) {}

    /** Per-stock hourly AI analysis snapshot used to populate plan suggestions. */
    public record TradeAnalysisModel(
            String stockCode,
            int version,
            LocalDateTime generatedAt,
            String provider,
            String model,
            String summary,
            List<String> buySuggestions,
            List<String> sellSuggestions,
            List<String> riskWarnings,
            BigDecimal confidence) {}

    public record StockMarket(
            String code,
            String name,
            String industry,
            BigDecimal price,
            BigDecimal changePercent,
            BigDecimal turnover,
            BigDecimal averageTurnover20,
            BigDecimal ma5,
            BigDecimal ma20,
            BigDecimal ma60,
            BigDecimal ma120,
            BigDecimal high20,
            BigDecimal high60,
            BigDecimal rsi14,
            BigDecimal macd,
            BigDecimal macdSignal,
            BigDecimal volumeRatio,
            BigDecimal roe,
            BigDecimal profitGrowth,
            BigDecimal revenueGrowth,
            BigDecimal debtRatio,
            BigDecimal netInflow,
            BigDecimal limitUpPrice,
            BigDecimal limitDownPrice,
            boolean st,
            boolean suspended,
            int listingDays,
            LocalDate lastTradingDate,
            String board,
            String quoteStatus,
            LocalDateTime quoteTime,
            String majorEventType,
            String majorEventTitle,
            String majorEventSummary,
            LocalDateTime majorEventTime,
            String majorEventUrl,
            String dataStatus) {}

    public record HardFilterResult(boolean passed, List<String> reasons) {}

    public record FactorScores(
            int businessModel,
            int industryProspect,
            int competitiveAdvantage,
            int financialQuality,
            int growth,
            int valuation,
            int catalyst,
            int risk,
            int total,
            int riskPenalty,
            int finalScore,
            BigDecimal buyLow,
            BigDecimal buyHigh,
            List<String> explanations,
            int availableMaximum,
            BigDecimal coveragePercent) {
        public int trend() { return industryProspect; }
        public int momentum() { return growth; }
        public int volumePrice() { return valuation; }
        public int fundamental() { return financialQuality; }
        public int capital() { return catalyst; }
        public int qualityValuation() { return competitiveAdvantage; }
        public int aiSuggestion() { return businessModel; }
    }

    public record StockPoolItem(
            StockMarket stock,
            HardFilterResult hardFilter,
            FactorScores scores,
            String action,
            List<String> recommendationReasons,
            StockContext stockContext,
            AiCompanyAnalysis companyAnalysis) {}

    public record AiTradeAdvice(
            boolean available,
            BigDecimal buyLow,
            BigDecimal buyHigh,
            BigDecimal nextSupportPrice,
            BigDecimal takeProfit1,
            BigDecimal takeProfit2,
            BigDecimal hardStop,
            BigDecimal trailingStop,
            String bandAdvice,
            List<String> suggestions,
            BigDecimal confidence) {
        public static AiTradeAdvice unavailable() {
            return new AiTradeAdvice(false, null, null, null, null, null, null, null,
                    "AI价格建议不可用", List.of(), BigDecimal.ZERO);
        }
    }

    public record StockContext(
            boolean sentimentAvailable,
            int sentimentScore,
            String sentimentLevel,
            BigDecimal sentimentAdjustment,
            boolean newsAvailable,
            int positiveNewsCount,
            int negativeNewsCount,
            String newsSummary,
            List<String> highlights,
            boolean aiScoreAvailable,
            int aiScore,
            String aiAdvice,
            AiTradeAdvice priceAdvice) {}

    public record AiCompanyAnalysis(
            boolean available,
            String businessDescription,
            String outlook,
            String futureTrend,
            String risk,
            BigDecimal confidence) {
        public static AiCompanyAnalysis unavailable() {
            return new AiCompanyAnalysis(false, "主营信息不可用", "无法判断", "无法判断", "AI分析不可用，不参与评分", BigDecimal.ZERO);
        }
    }

    public record MarketIndexQuote(
            String code,
            String name,
            BigDecimal price,
            BigDecimal change,
            BigDecimal changePercent,
            String quoteStatus,
            LocalDateTime quoteTime) {}

    public record RecommendationSnapshotMeta(
            String slot,
            String source,
            LocalDateTime generatedAt,
            boolean latestSlot,
            boolean stale,
            String expectedSlot,
            String status) {}

    public record StockPoolResponse(
            LocalDate asOf,
            StrategyConfig config,
            int universeCount,
            int hardPassedCount,
            List<StockPoolItem> items,
            MarketContext marketContext,
            List<MarketIndexQuote> marketIndices,
            RecommendationSnapshotMeta snapshot) {}

    public record MarketContext(
            boolean sentimentAvailable,
            int sentimentScore,
            String regime,
            int risingCount,
            int fallingCount,
            int flatCount,
            int limitUpCount,
            int limitDownCount,
            BigDecimal averageChangePercent,
            BigDecimal marketAdjustment,
            boolean newsAvailable,
            int positiveNewsCount,
            int negativeNewsCount,
            String newsSummary,
            BigDecimal newsAdjustment,
            List<String> highlights) {}

    public record PortfolioAnalysis(
            boolean available,
            LocalDateTime analyzedAt,
            String marketOverview,
            String portfolioOverview,
            List<String> successPoints,
            List<String> mistakePoints,
            List<String> causes,
            List<String> nextSteps,
            List<String> riskWarnings,
            BigDecimal confidence,
            String message) {
        public static PortfolioAnalysis unavailable(String message) {
            return new PortfolioAnalysis(false, LocalDateTime.now(), "", "", List.of(), List.of(), List.of(),
                    List.of(), List.of(), BigDecimal.ZERO, message);
        }
    }

    public record PoolAddRequest(String code, String name, String industry) {}

    public record PositionRequest(
            BigDecimal buyPrice,
            BigDecimal quantity,
            LocalDate openedAt) {}

    public record AccountAssetRequest(BigDecimal totalAssets) {}

    public record AccountAssetSummary(
            BigDecimal totalAssets,
            LocalDateTime updatedAt) {}

    public record AiProviderConfig(
            String provider,
            String model,
            String baseUrl,
            boolean enabled,
            boolean apiKeyConfigured,
            String apiKeyMasked,
            LocalDateTime updatedAt) {}

    public record AiProviderUpdateRequest(
            String provider,
            String model,
            String baseUrl,
            String apiKey,
            Boolean enabled) {}

    public record MarketDataSourceConfig(
            String sourceKey,
            String name,
            String purpose,
            String adapter,
            boolean enabled,
            int priority,
            String endpoint,
            int timeoutSeconds,
            int retryCount,
            String userAgent,
            String referer,
            LocalDateTime updatedAt) {}

    public record MarketDataSourceConfigRequest(
            String sourceKey,
            String name,
            String purpose,
            String adapter,
            Boolean enabled,
            Integer priority,
            String endpoint,
            Integer timeoutSeconds,
            Integer retryCount,
            String userAgent,
            String referer) {}

    public record PlannedOrderRequest(
            String side,
            BigDecimal plannedPrice,
            BigDecimal quantity,
            LocalDate tradeDate) {}

    public record TradePlan(
            String signal,
            String band,
            BigDecimal buyLow,
            BigDecimal buyHigh,
            BigDecimal nextSupportPrice,
            BigDecimal forecastPrice,
            BigDecimal takeProfit1,
            BigDecimal takeProfit2,
            BigDecimal hardStop,
            BigDecimal trailingStop,
            String riskLevel,
            String riskColor,
            List<String> riskWarnings,
            List<String> swingHints,
            List<String> tSuggestions,
            PositionPlan positionPlan) {}

    /** Position context attached to the price plan so price and allocation advice stay consistent. */
    public record PositionPlan(
            String action,
            BigDecimal currentPositionPercent,
            BigDecimal maxPositionPercent,
            BigDecimal suggestedAddPercent,
            List<BigDecimal> suggestedBuyWeights,
            String advice,
            List<String> warnings) {
        public static PositionPlan unavailable() {
            return new PositionPlan("暂不判断仓位", null, null, null, List.of(),
                    "缺少持仓或账户资产数据，暂不生成仓位建议", List.of());
        }
    }

    public record PriceHistoryPoint(
            LocalDate date,
            BigDecimal price) {}

    public record AnalysisAccuracy(
            int predictionSamples,
            int predictionCorrect,
            BigDecimal predictionRate,
            String predictionLabel,
            String predictionMethod,
            int operationSamples,
            int operationCorrect,
            BigDecimal operationRate,
            String operationLabel,
            String operationMethod,
            java.time.LocalDateTime calculatedAt) {}

    public record StockPoolEntry(
            String code,
            LocalDate addedAt,
            String addedBy,
            StockPoolItem analysis,
            TradePlan tradePlan,
            PositionAnalysis position,
            PlannedOrderAnalysis plannedOrder,
            TradeExecutionSummary todayTrade,
            List<PriceHistoryPoint> priceHistory,
            AnalysisAccuracy analysisAccuracy) {}

    public record PositionAnalysis(
            boolean hasPosition,
            BigDecimal buyPrice,
            BigDecimal quantity,
            BigDecimal currentPrice,
            BigDecimal marketValue,
            BigDecimal pnlAmount,
            BigDecimal pnlPercent,
            String status,
            String action,
            String actionColor,
            List<String> suggestions,
            List<String> riskWarnings,
            BigDecimal accountTotalAssets,
            BigDecimal positionPercent,
            BigDecimal maxPositionPercent,
            String allocationAdvice) {}

    /** The persisted simulated position row, kept separate from the calculated risk analysis. */
    public record PositionRecord(
            boolean found,
            BigDecimal quantity,
            BigDecimal availableQuantity,
            BigDecimal avgCost,
            BigDecimal highestPrice,
            LocalDate openedAt,
            LocalDateTime updatedAt,
            String source) {}

    public record PlannedOrderAnalysis(
            boolean hasPlan,
            String side,
            BigDecimal plannedPrice,
            BigDecimal quantity,
            LocalDate tradeDate,
            BigDecimal currentPrice,
            BigDecimal gapPercent,
            String status,
            String action,
            String actionColor,
            List<String> suggestions,
            List<String> riskWarnings,
            BigDecimal accountTotalAssets,
            BigDecimal projectedPositionPercent,
            BigDecimal maxPositionPercent,
            String allocationAdvice,
            String decision,
            String decisionReason,
            BigDecimal successProbability,
            String probabilityReason) {}

    public record TradeExecutionSummary(
            boolean hasTrade,
            LocalDate tradeDate,
            String side,
            BigDecimal executedPrice,
            BigDecimal quantity,
            BigDecimal amount,
            BigDecimal currentPrice,
            BigDecimal pnlAmount,
            BigDecimal pnlPercent,
            String status,
            List<String> suggestions) {}

    public record ManagedPoolResponse(
            LocalDate asOf,
            Set<String> codes,
            List<StockPoolEntry> items,
            MarketContext marketContext,
            List<MarketIndexQuote> marketIndices) {}

    public record SellDecision(
            String code,
            int sellScore,
            boolean hardStopTriggered,
            boolean trailingStopTriggered,
            boolean shouldSell,
            String reason) {}

    public record PositionSizing(
            BigDecimal marketExposure,
            BigDecimal singlePosition,
            BigDecimal industryExposure,
            BigDecimal cashReserve,
            String marketRegime) {}
}
